version: "3.3"

services:

  traefik:
    image: "traefik:v2.6"
    container_name: "traefik"
    command:
      - "--providers.docker=true"
      - "--providers.docker.exposedbydefault=false"
      - "--entrypoints.web.address=:80"
      - "--entrypoints.websecure.address=:443"
      - "--entrypoints.websecure.http.tls=true"
      - "--entrypoints.web.http.redirections.entryPoint.to=websecure"
      - "--entrypoints.web.http.redirections.entryPoint.scheme=https"
      - "--providers.file.directory=/configuration/"
      - "--providers.file.watch=true"

    ports:
      - "80:80"
      - "443:443"
    volumes:
      - "./certs:/certs"
      - "./traefik:/configuration"
      - "/var/run/docker.sock:/var/run/docker.sock:ro"

  keycloak:
    restart: always
    image: quay.io/keycloak/keycloak:17.0
    environment:
      - KEYCLOAK_ADMIN=admin
      - KEYCLOAK_ADMIN_PASSWORD=admin
      - KC_HOSTNAME=auth.localhost
      - KC_DB=dev-file
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.keycloak.rule=Host(`auth.localhost`)"
      - "traefik.http.routers.keycloak.entrypoints=websecure"
      - "traefik.http.routers.keycloak.tls=true"
      - "traefik.http.services.keycloak.loadbalancer.server.port=8080"
    entrypoint: /opt/keycloak/bin/kc.sh start-dev --proxy edge --hostname auth.localhost